### ISSUE TITLE
Add AI support for uniset MACs

### ISSUE THREAD

**Issue by iindex** [KatekovAnton/MAXTouch-docs#102] opened 2021-11-08 10:00 UTC
Add AI support for uniset MACs, ID: 85
https://macsgame.com/game/uniset/85.html

And make it default

**Comment by Malakia1** [comment] 2021-11-08 10:07
Duplicate of https://github.com/KatekovAnton/MAXTouch-docs/issues/99

**Comment by KatekovAnton** [comment] 2021-11-08 15:30
fixed in v16.1.2 beta 1

**Closed by KatekovAnton** 2021-11-08 15:30 UTC
